language: objective-c
osx_image: xcode9
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - IOS_SIMULATOR_SDK=iphonesimulator11
    - IOS_SDK=iphoneos11
    - PROJECT_DIR=`pwd`
  matrix:
    - DESTINATION="OS=11.0,name=iPhone SE"  POD_LINT="YES"  $SDK="$IOS_SIMULATOR_SDK"
before_install:
  - gem install cocoapods -v '1.1.0' --no-document
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - pod --version
  - pwd
  - cd $PROJECT_DIR/Tests;
  - pwd;
  - pod install;
  - xcodebuild -workspace BlueCapKitTests.xcworkspace -scheme BlueCapKitTests -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES build test | xcpretty -c;

